/* ============================================================================
 * client_model.js — pure, self-contained recompute functions for the
 * space-launches story. No raw-data access needed: the data slices below are
 * generated by code/analyze.py (-> code/client_data.json) and embedded here so
 * the Programmer can inline this ONE file. Every function is closed-form and
 * runs in well under 1ms, so the in-browser explorable + the verify layer can
 * recompute any headline live from reader inputs.
 *
 * Provenance: all numbers reproduce code/analyze.py on launches.csv (5,726
 * orbital launch attempts, 1957-2018; SU+RU merged; F+I-ESA+I-ELDO = Europe;
 * 2018 is a PARTIAL year, Jan-Oct only).
 * ==========================================================================*/

const CLIENT_DATA = {
  countries: ["USSR/Russia", "USA", "China", "Europe", "Japan", "India", "Other"],
  // year, then one count per country (same order as `countries`)
  matrix: [
    [1957,2,1,0,0,0,0,0],[1958,5,22,0,0,0,0,0],[1959,4,18,0,0,0,0,0],[1960,8,29,0,0,0,0,0],
    [1961,9,41,0,0,0,0,0],[1962,22,59,0,0,0,0,0],[1963,23,46,0,0,0,0,0],[1964,36,63,0,0,0,0,0],
    [1965,53,70,0,1,0,0,0],[1966,51,77,0,1,2,0,0],[1967,74,61,0,2,1,0,1],[1968,79,48,0,1,0,0,0],
    [1969,81,41,0,1,1,0,0],[1970,87,28,1,2,2,0,2],[1971,91,34,1,3,2,0,3],[1972,79,32,0,0,1,0,1],
    [1973,88,25,1,0,0,0,0],[1974,85,23,2,0,1,0,2],[1975,93,30,3,3,2,0,1],[1976,100,26,3,0,2,0,0],
    [1977,102,26,0,0,2,0,0],[1978,91,33,1,0,3,0,0],[1979,88,16,1,1,2,1,0],[1980,89,14,0,1,2,1,0],
    [1981,100,19,1,2,3,1,0],[1982,108,18,1,1,1,0,0],[1983,100,22,1,2,3,1,0],[1984,97,22,3,4,3,0,0],
    [1985,100,18,1,4,2,0,0],[1986,94,9,2,3,2,0,0],[1987,96,9,2,2,3,1,0],[1988,94,11,4,7,2,1,2],
    [1989,75,18,0,7,2,0,0],[1990,79,27,5,6,3,0,1],[1991,61,19,1,8,2,0,0],[1992,55,29,4,7,1,1,0],
    [1993,48,25,1,7,1,1,0],[1994,49,27,5,8,2,2,0],[1995,33,30,3,11,1,0,1],[1996,27,33,4,11,1,1,0],
    [1997,29,38,6,12,2,1,1],[1998,25,36,6,11,2,0,2],[1999,21,31,4,16,1,1,3],[2000,31,29,5,16,0,0,2],
    [2001,23,23,1,8,1,2,0],[2002,24,18,5,12,3,1,1],[2003,19,26,6,6,3,2,0],[2004,21,19,8,3,0,1,1],
    [2005,23,16,6,8,2,1,0],[2006,23,23,6,6,6,1,0],[2007,20,20,10,9,2,3,1],[2008,24,20,11,7,1,3,1],
    [2009,31,25,6,7,3,2,3],[2010,28,15,15,6,2,3,2],[2011,28,19,19,7,3,3,1],[2012,24,16,19,10,2,2,5],
    [2013,29,20,15,7,3,3,1],[2014,30,24,16,11,4,4,1],[2015,24,20,19,11,4,5,1],[2016,17,22,22,11,4,7,2],
    [2017,18,30,18,11,7,5,1],[2018,10,27,28,6,5,4,0]   // 2018 = PARTIAL (Jan-Oct)
  ],
  partial2018MonthsElapsed: 10,
  // [successes, attempts] per group
  successByCountry: {"USSR/Russia":[3024,3178],"USA":[1585,1716],"China":[289,302],"Europe":[294,307],"Japan":[106,115],"India":[58,65],"Other":[28,43]},
  successByType: {"state":[4462,4776],"private":[857,880],"startup":[65,70]},
  successByDecade: {"1950s":[24,52],"1960s":[854,982],"1970s":[1163,1226],"1980s":[1156,1191],"1990s":[849,889],"2000s":[629,650],"2010s":[709,736]}
};

/* --- model 1: launchSnapshot(year) --------------------------------------
 * INPUT : year (1957..2018)
 * OUTPUT: { year, partial, counts{country:n}, total, shares{country:%},
 *           leader, duopolyShare }  where duopolyShare = (USA+USSR/Russia)/total
 * Powers the year-scrubber launch-race explorable and the "duel -> crowd"
 * reveal (watch duopolyShare fall from ~99% to ~54%). */
function launchSnapshot(year) {
  const row = CLIENT_DATA.matrix.find(r => r[0] === Number(year));
  if (!row) return null;
  const C = CLIENT_DATA.countries;
  const counts = {}; let total = 0;
  C.forEach((c, i) => { counts[c] = row[i + 1]; total += row[i + 1]; });
  const shares = {};
  C.forEach(c => { shares[c] = total ? +(100 * counts[c] / total).toFixed(1) : 0; });
  let leader = C[0];
  C.forEach(c => { if (counts[c] > counts[leader]) leader = c; });
  const duopolyShare = total ? +(100 * (counts["USA"] + counts["USSR/Russia"]) / total).toFixed(1) : 0;
  return { year: Number(year), partial: Number(year) === 2018, counts, total, shares, leader, duopolyShare };
}

/* --- model 2: cumulativeThrough(year) -----------------------------------
 * INPUT : year
 * OUTPUT: { country: cumulativeLaunches } summed 1957..year + ranked[]
 * Powers a cumulative "who is ahead" bar race. */
function cumulativeThrough(year) {
  const C = CLIENT_DATA.countries;
  const cum = {}; C.forEach(c => cum[c] = 0);
  for (const r of CLIENT_DATA.matrix) {
    if (r[0] > Number(year)) break;
    C.forEach((c, i) => cum[c] += r[i + 1]);
  }
  const ranked = C.map(c => [c, cum[c]]).sort((a, b) => b[1] - a[1]);
  return { cum, ranked };
}

/* --- model 3: successRate(scope, key) -----------------------------------
 * INPUT : scope in {"country","type","decade"}, key (e.g. "China","startup","1980s")
 * OUTPUT: { successes, attempts, rate }  rate = successes/attempts*100
 * Powers the success-rate calculator + verify-layer recompute. */
function successRate(scope, key) {
  const tbl = scope === "country" ? CLIENT_DATA.successByCountry
            : scope === "type"    ? CLIENT_DATA.successByType
            : CLIENT_DATA.successByDecade;
  const pair = tbl[key];
  if (!pair) return null;
  return { successes: pair[0], attempts: pair[1], rate: +(100 * pair[0] / pair[1]).toFixed(1) };
}

/* --- model 4: annualize(partialCount, monthsElapsed) --------------------
 * INPUT : partialCount, monthsElapsed (default 10 = dataset's Jan-Oct 2018)
 * OUTPUT: projected full-year count = partialCount * 12 / monthsElapsed
 * Lets the reader recompute the partial-2018 caveat honestly (naive linear
 * pro-rate; NOT a forecast). e.g. China 28 -> ~33.6 (external actual: 39). */
function annualize(partialCount, monthsElapsed) {
  const m = monthsElapsed || CLIENT_DATA.partial2018MonthsElapsed;
  return +(Number(partialCount) * 12 / m).toFixed(1);
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = { CLIENT_DATA, launchSnapshot, cumulativeThrough, successRate, annualize };
}
