"""
07_client_models.py — emit the interactive centrepieces (client-side, pure-JS, closed-form).
  ana_12 : "Re-weight the rankings" recomputer — reader sets pillar weights, gets a re-ranked
           top-N, proving 'best university' is a weighting choice. Writes code/client_model.js.
  ana_13 : per-university lookup — its four system ranks + OpenAlex ranks + spread.
Run from DATA_DIR:  PYTHONUTF8=1 py "<PROJECT_DIR>/code/07_client_models.py"
"""
import os
import sys
import json
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import common as c  # noqa: E402


def _int(v):
    try:
        return int(v)
    except (ValueError, TypeError):
        return None

m = pd.read_csv(os.path.join(HERE, "core_master.csv"))
the = c.load_the()
qs = c.load_qs()
m = (m.merge(the[["key", "teaching", "citations", "international"]], on="key", how="left")
       .merge(qs[["key", "ar score", "cpf score"]], on="key", how="left"))

# coerce THE/QS pillar columns to numeric (THE stores '-' placeholders as objects)
for col in ["teaching", "citations", "international", "ar score", "cpf score"]:
    m[col] = pd.to_numeric(m[col], errors="coerce")

# five real, 0-100 normalized pillars per university (volume scaled within the core)
maxw = m["works_count"].max()
m["rep"] = m["ar score"].round(1)                         # QS Academic Reputation survey
m["cite"] = m["citations"].round(1)                       # THE field-normalised citation impact
m["teach"] = m["teaching"].round(1)                       # THE teaching pillar
m["intl"] = m["international"].round(1)                    # THE international outlook
m["vol"] = (100 * m["works_count"] / maxw).round(1)       # OpenAlex raw output volume (0-100)

slice_cols = ["the_name", "country", "rep", "cite", "teach", "intl", "vol"]
data = [{"name": r.the_name, "country": r.country, "rep": r.rep, "cite": r.cite,
         "teach": r.teach, "intl": r.intl, "vol": r.vol}
        for r in m[slice_cols].itertuples(index=False)]

PRESETS = {
    "balanced":     {"rep": 1, "cite": 1, "teach": 1, "intl": 1, "vol": 1},
    "qs_like":      {"rep": 5, "cite": 2, "teach": 2, "intl": 1, "vol": 0},   # reputation-heavy
    "the_like":     {"rep": 3, "cite": 3, "teach": 3, "intl": 1, "vol": 0},   # rep+citations blend
    "arwu_like":    {"rep": 0, "cite": 3, "teach": 0, "intl": 0, "vol": 4},   # research output/volume
    "output_only":  {"rep": 0, "cite": 0, "teach": 0, "intl": 0, "vol": 1},   # pure OpenAlex volume
}


def recompute(weights, topn=None):
    """Mirror of the JS: weighted 0-100 pillar blend -> re-ranked list."""
    tot = sum(weights.values())
    scored = []
    for d in data:
        s = sum(weights[k] * d[k] for k in ["rep", "cite", "teach", "intl", "vol"]) / (tot if tot else 1)
        scored.append((d["name"], round(s, 2)))
    scored.sort(key=lambda x: x[1], reverse=True)
    out = [{"rank": i + 1, "name": n, "score": s} for i, (n, s) in enumerate(scored)]
    return out[:topn] if topn else out

# --- ana_12: the re-weight recomputer (demonstrate the #1 FLIPS with the weights) ---
print("=== ana_12 ===")
print("Client model over %d common-core universities, 5 real 0-100 pillars "
      "(rep=QS Academic Reputation, cite=THE citations, teach=THE teaching, "
      "intl=THE international, vol=OpenAlex works)." % len(data))
for preset in ["balanced", "qs_like", "the_like", "arwu_like", "output_only"]:
    top5 = recompute(PRESETS[preset], 5)
    print(f"\n[{preset}] weights={PRESETS[preset]}")
    for row in top5:
        print(f"   #{row['rank']} {row['name']} ({row['score']})")
# headline: how many DIFFERENT universities are #1 across the presets
winners = {p: recompute(PRESETS[p], 1)[0]["name"] for p in PRESETS}
print("\n#1 under each preset:", winners)
print("Distinct #1s produced just by moving the sliders:", len(set(winners.values())))

# write client_model.js (identical algorithm + real data slice + presets)
js = f"""// client_model.js — Re-weight the rankings (Data2Story interactive centrepiece)
// Generated by code/07_client_models.py from the 218-university common core.
// Five REAL 0-100 pillars per university:
//   rep = QS Academic Reputation survey score
//   cite = THE field-normalised citation-impact pillar
//   teach = THE teaching pillar
//   intl = THE international-outlook pillar
//   vol = OpenAlex raw output volume (works_count scaled to 0-100 within the core)
// "Best university" is whatever these weights decide — that IS the story.

const REWEIGHT_DATA = {json.dumps(data, ensure_ascii=False)};

const REWEIGHT_PRESETS = {json.dumps(PRESETS)};

// weights: {{rep,cite,teach,intl,vol}} (any non-negative numbers). Returns
// [{{rank,name,score}}...] sorted best-first. Pure, closed-form, O(n log n) — <1ms.
function reweightRankings(weights, topN) {{
  const keys = ["rep", "cite", "teach", "intl", "vol"];
  let tot = keys.reduce((a, k) => a + (+weights[k] || 0), 0);
  if (tot === 0) tot = 1;
  const scored = REWEIGHT_DATA.map(d => {{
    let s = 0;
    for (const k of keys) s += (+weights[k] || 0) * d[k];
    return {{ name: d.name, country: d.country, score: Math.round((s / tot) * 100) / 100 }};
  }});
  scored.sort((a, b) => b.score - a.score);
  scored.forEach((r, i) => (r.rank = i + 1));
  return topN ? scored.slice(0, topN) : scored;
}}

// Per-university lookup: its four commercial ranks + OpenAlex ranks + spread.
const RANK_LOOKUP = {json.dumps(
    {r.the_name: {"country": r.country, "THE": _int(r.the_rank), "ARWU": _int(r.arwu_rank),
                  "CWUR": _int(r.cwur_rank), "QS": _int(r.qs_rank),
                  "OpenAlex_works": _int(r.oa_rank_works), "OpenAlex_cites": _int(r.oa_rank_cites),
                  "spread": _int(max(r.the_rank, r.arwu_rank, r.cwur_rank, r.qs_rank) -
                                 min(r.the_rank, r.arwu_rank, r.cwur_rank, r.qs_rank))}
     for r in m.itertuples(index=False)}, ensure_ascii=False)};

if (typeof module !== "undefined") module.exports = {{ REWEIGHT_DATA, REWEIGHT_PRESETS, reweightRankings, RANK_LOOKUP }};
"""
with open(os.path.join(HERE, "client_model.js"), "w", encoding="utf-8") as f:
    f.write(js)
print("\nWrote", os.path.join(HERE, "client_model.js"),
      "(%d-university slice + presets + lookup)" % len(data))

# --- ana_13: per-university lookup sample (powers a 'find your university' widget) ---
print("=== ana_13 ===")
m["spread"] = m[["the_rank", "arwu_rank", "cwur_rank", "qs_rank"]].max(axis=1) - \
              m[["the_rank", "arwu_rank", "cwur_rank", "qs_rank"]].min(axis=1)
look_cols = ["the_name", "country", "the_rank", "arwu_rank", "cwur_rank", "qs_rank",
             "oa_rank_works", "oa_rank_cites", "spread"]
print("Sample lookup rows (the widget returns one such row per searched university):")
sample = m[m.the_name.isin(["Harvard University", "California Institute of Technology",
                            "University of Michigan", "Peking University",
                            "University of California, Berkeley", "Princeton University"])]
print(sample[look_cols].to_string(index=False))
print("Lookup covers all %d common-core universities." % len(m))
