"""
Emit client_model.js — an in-browser port of the vetted Elo->Poisson->Monte-Carlo
forecast, so a reader-facing explorable can recompute champion odds live (e.g. nudge
a team's Elo, re-run the bracket). Data is inlined; the JS sim mirrors simulate.py.

Run:  python make_client_model.py   ->  writes ../client_model.js  (and ../model/client_model.js copy)
"""
import sys, json
try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass
from pathlib import Path
import pandas as pd
import elo, poisson

D = Path(__file__).resolve().parent.parent          # worldcup_2026
teams_df = pd.read_csv(D / "teams.csv", encoding="utf-8")
teams = teams_df["team"].tolist()
group_of = dict(zip(teams_df["team"], teams_df["group"]))
groups = sorted(teams_df["group"].unique())
GROUPS = {g: teams_df[teams_df["group"] == g]["team"].tolist() for g in groups}

elo_now = elo.rating_table(elo.compute_elo(cutoff=elo.TODAY_CUTOFF), teams)
p = poisson.calibrate()

m = pd.read_csv(D / "matches.csv", encoding="utf-8")
grp = m[m["stage"] == "group"]
played = grp[grp["status"] == "played"]
sched = grp[grp["status"] == "scheduled"]

# baseline standings from the 28 played group games
base = {t: {"pts": 0, "gd": 0, "gf": 0} for t in teams}
for h, a, hg, ag in zip(played["home"], played["away"], played["home_goals"], played["away_goals"]):
    hg, ag = int(hg), int(ag)
    base[h]["gf"] += hg; base[a]["gf"] += ag
    base[h]["gd"] += hg - ag; base[a]["gd"] += ag - hg
    if hg > ag: base[h]["pts"] += 3
    elif hg == ag: base[h]["pts"] += 1; base[a]["pts"] += 1
    else: base[a]["pts"] += 3

SCHED = [[h, a, g] for h, a, g in zip(sched["home"], sched["away"], sched["group"])]

br = json.loads((D / "bracket_rules.json").read_text(encoding="utf-8"))
r32 = {int(k): v for k, v in br["r32_slots"].items()}
tree = {int(k): v for k, v in br["bracket_tree"].items()}
host_matches = [74, 77, 79, 80, 81, 82, 85, 87]
# compact best-thirds: sortedGroupKey -> {matchId: groupLetter}
best3 = {}
for key, val in br["best_thirds_allocation"]["table"].items():
    best3[key] = {str(mid): str(slot)[-1] for mid, slot in val["assign"].items()}

# published champion odds (exact baseline to show at rest)
champ_pub = {}
co = pd.read_csv(D / "forecast_outputs" / "champion_odds.csv", encoding="utf-8")
for t, pc in zip(co["team"], co["p_champion"]):
    champ_pub[t] = round(float(pc), 4)

payload = {
    "as_of": "2026-06-24", "elo_cutoff": elo.TODAY_CUTOFF,
    "elo": {t: round(elo_now[t], 1) for t in teams},
    "params": {"a": p["a"], "b": p["b"], "mu": p["mu_tot"]},
    "groups": GROUPS, "group_of": group_of,
    "played": base, "sched": SCHED,
    "r32": r32, "tree": tree, "hostMatches": host_matches, "best3": best3,
    "championPublished": champ_pub,
}

JS = """// client_model.js  (auto-generated by make_client_model.py — do not hand-edit)
// In-browser port of the vetted Elo->Poisson->Monte-Carlo 2026 World Cup forecast.
// Lets an explorable recompute champion odds live. At rest, show DATA.championPublished
// (the exact 100k-sim figures); when the reader changes an input, call simulate(n, overrides).
window.WC_MODEL = (function () {
  const DATA = __PAYLOAD__;
  const A = DATA.params.a, B = DATA.params.b, MU = DATA.params.mu;

  function eloOf(t, ov) { return (DATA.elo[t] || 1500) + ((ov && ov[t]) || 0); }

  // Poisson sampler (Knuth)
  function pois(l) { const Lx = Math.exp(-l); let k = 0, prod = 1;
    do { k++; prod *= Math.random(); } while (prod > Lx); return k - 1; }

  // match goal rates (neutral venue, like the published model)
  function lambdas(eh, ea) { const sup = A + B * (eh - ea);
    return [Math.max(0.05, (MU + sup) / 2), Math.max(0.05, (MU - sup) / 2)]; }

  // P(home win/draw/away) over a Poisson grid
  function matchProb(eh, ea) {
    const [lh, la] = lambdas(eh, ea), MAXG = 10;
    const ph = [], pa = []; let fh = Math.exp(-lh), fa = Math.exp(-la);
    for (let k = 0; k <= MAXG; k++) {
      ph.push(fh); pa.push(fa);
      fh *= lh / (k + 1); fa *= la / (k + 1);
    }
    let pH = 0, pD = 0, pA = 0;
    for (let i = 0; i <= MAXG; i++) for (let j = 0; j <= MAXG; j++) {
      const pr = ph[i] * pa[j]; if (i > j) pH += pr; else if (i === j) pD += pr; else pA += pr; }
    const s = pH + pD + pA; return [pH / s, pD / s, pA / s];
  }
  // knockout advance prob: win in 90 + draw * Elo win-expectation (stands in for ET/pens)
  function advProb(eh, ea) { const pp = matchProb(eh, ea);
    const we = 1 / (1 + Math.pow(10, -(eh - ea) / 400)); return pp[0] + pp[1] * we; }

  function rankKey(st) { return st.pts * 1e4 + (st.gd + 100) * 100 + st.gf + Math.random() * 0.5; }

  function simulate(nSims, overrides) {
    nSims = nSims || 3000; overrides = overrides || {};
    const champ = {}; DATA.groups && Object.values(DATA.groups).flat().forEach(t => champ[t] = 0);
    const groups = Object.keys(DATA.groups);
    for (let s = 0; s < nSims; s++) {
      // standings start from played baseline
      const st = {}; for (const t in DATA.played) st[t] = { pts: DATA.played[t].pts, gd: DATA.played[t].gd, gf: DATA.played[t].gf };
      // remaining group matches
      for (const [h, a] of DATA.sched) {
        const hg = pois(lambdas(eloOf(h, overrides), eloOf(a, overrides))[0]);
        const ag = pois(lambdas(eloOf(h, overrides), eloOf(a, overrides))[1]);
        st[h].gf += hg; st[a].gf += ag; st[h].gd += hg - ag; st[a].gd += ag - hg;
        if (hg > ag) st[h].pts += 3; else if (hg === ag) { st[h].pts += 1; st[a].pts += 1; } else st[a].pts += 3;
      }
      // rank each group
      const winner = {}, runner = {}, thirds = [];
      for (const g of groups) {
        const ranked = DATA.groups[g].slice().sort((x, y) => rankKey(st[y]) - rankKey(st[x]));
        winner[g] = ranked[0]; runner[g] = ranked[1];
        thirds.push({ g, t: ranked[2], k: rankKey(st[ranked[2]]) });
      }
      // best 8 thirds
      thirds.sort((x, y) => y.k - x.k);
      const top8 = thirds.slice(0, 8);
      const key = top8.map(o => o.g).sort().join("");
      const assign = DATA.best3[key] || {};
      const thirdTeamByGroup = {}; top8.forEach(o => thirdTeamByGroup[o.g] = o.t);
      // resolve R32 participants
      const W = {}, L = {};
      function slotTeam(code, mid) {
        if (code[0] === "1") return winner[code[1]];
        if (code[0] === "2") return runner[code[1]];
        // best-third slot: use the official assignment for this match
        const gLetter = assign[String(mid)];
        return thirdTeamByGroup[gLetter];
      }
      for (let mid = 73; mid <= 88; mid++) {
        const sdef = DATA.r32[mid];
        const h = slotTeam(sdef.home, mid), a = slotTeam(sdef.away, mid);
        const eh = eloOf(h, overrides), ea = eloOf(a, overrides);
        const win = Math.random() < advProb(eh, ea) ? h : a;
        W[mid] = win; L[mid] = win === h ? a : h;
      }
      for (let mid = 89; mid <= 104; mid++) {
        const nd = DATA.tree[mid];
        const feed = side => side.take === "winner" ? W[side.from_match] : L[side.from_match];
        const h = feed(nd.home), a = feed(nd.away);
        const win = Math.random() < advProb(eloOf(h, overrides), eloOf(a, overrides)) ? h : a;
        W[mid] = win; L[mid] = win === h ? a : h;
      }
      champ[W[104]] = (champ[W[104]] || 0) + 1;
    }
    const out = {}; for (const t in champ) out[t] = champ[t] / nSims;
    return out; // {team: p_champion}
  }

  return { DATA: DATA, simulate: simulate, matchProb: matchProb, advProb: advProb,
           teams: Object.keys(DATA.elo) };
})();
if (typeof module !== "undefined") module.exports = window.WC_MODEL ? null : null;
"""

js_out = JS.replace("__PAYLOAD__", json.dumps(payload, ensure_ascii=False))
# the IIFE assigns to window.WC_MODEL; for node testing, shim window first.
out_path = D / "model" / "client_model.js"
out_path.write_text(js_out, encoding="utf-8")
# also place a copy at dataset root so the pipeline/Programmer can find it easily
(D / "client_model.js").write_text(js_out, encoding="utf-8")
print("wrote", out_path, "and", D / "client_model.js")
print("size:", len(js_out), "bytes")
print("published champion top5:", sorted(champ_pub.items(), key=lambda kv: -kv[1])[:5])
